import type { GenreDetailedConfig, GenreFreshnessRule, GenreScoringWeights, RiskLevel } from "@/lib/genres/types";

// 33ジャンル詳細設定（仕様書「ClaudeCode_33ジャンル統合エンジン実装プロンプト_完全版.md」
// 第18章「全33ジャンル詳細仕様」を情報を省略せず設定データへ変換したもの）。
// 巨大なif/switchを避けるため、ジャンル1〜26に共通するボイラープレート
// （三層構造の用途区分・鮮度テーブル・除外ルール前半）はビルダー関数に集約し、
// ジャンルごとに異なる部分（対象範囲・情報源例・情報タイプ優先度・固有の除外ルール等）
// のみを個別に指定する。ジャンル27〜33は仕様書の記述が個別化されているため、
// ビルダーに渡すパラメータでその差異を表現する。

const IMPLEMENTATION_DATE = "2026-07-15T00:00:00.000Z";

const DEFAULT_SCORING_WEIGHTS: GenreScoringWeights = {
  relevance: 0.21,
  freshness: 0.15,
  reliability: 0.16,
  novelty: 0.09,
  actionability: 0.1,
  urgency: 0.08,
  regionalFit: 0.06,
  userPreference: 0.06,
  sourceDiversity: 0.03,
  visualQuality: 0.03,
  evergreenValue: 0.03,
};

function scoringWeights(overrides: Partial<GenreScoringWeights> = {}): GenreScoringWeights {
  return { ...DEFAULT_SCORING_WEIGHTS, ...overrides };
}

// 仕様書5-7「三層構造」の用途区分は全ジャンル共通のボイラープレート。
const TIER1_PURPOSES = [
  "正式な開催・発売・出演",
  "日時",
  "場所",
  "料金",
  "受付",
  "変更",
  "中止",
  "制度",
  "仕様",
  "結果",
  "安全",
  "回収",
  "公式見解",
];
const TIER2_PURPOSES = ["背景", "比較", "専門解説", "評価", "市場動向", "歴史的位置づけ", "業界内の意味"];
const TIER3_PURPOSES = [
  "使用感",
  "現地の様子",
  "混雑",
  "話題性",
  "売り切れ",
  "在庫",
  "雰囲気",
  "利用者の困りごと",
  "トレンド兆候",
];

const TIER1_ALLOWED_USES = ["正式発表の確定", "日時・場所・料金の確定", "安全・回収情報の確定"];
const TIER1_PROHIBITED_USES: string[] = [];
const TIER2_ALLOWED_USES = ["背景説明", "比較", "専門的評価"];
const TIER2_PROHIBITED_USES = ["公式発表の代替として単独確定"];
const TIER3_ALLOWED_USES = ["発見", "反応・利用体験の把握"];
const TIER3_PROHIBITED_USES = [
  "医療・健康効果の確定",
  "法制度の確定",
  "災害の確定",
  "安全性の確定",
  "営業・開催の確定",
  "正式料金の確定",
  "真贋の確定",
  "事故原因の確定",
  "結果の確定",
  "譲渡の正当性の確定",
  "入国条件の確定",
  "回収対象の確定",
];

// 仕様書1〜26章に共通する鮮度テーブル。27〜33章は個別のテーブルを持つため上書きする。
const STANDARD_FRESHNESS_RULES: GenreFreshnessRule[] = [
  { informationType: "速報・当日情報", preferredPeriod: "表示時に再確認", revalidateAtDisplayTime: true },
  {
    informationType: "新作・イベント",
    preferredPeriod: "発表後から終了・発売後30〜90日",
    revalidateAtDisplayTime: false,
  },
  { informationType: "基本解説", preferredPeriod: "長期利用可能。ただし最新仕様を確認", revalidateAtDisplayTime: false },
];

const STANDARD_QUALITY_RULES_PREFIX = [
  "公式発表と推測・口コミ・感想を分離する。",
  "古い記事を現在の予定・状態として表示しない。",
  "無断転載、違法配信、なりすまし、権利侵害コンテンツを除外する。",
  "生成画像を実在の人物・商品・店舗・作品の公式写真として表示しない。",
];

interface StandardGenreParams {
  genreId: string;
  genreNumber: number;
  displayName: string;
  description: string;
  targetScope: string[];
  tier1ExampleSources: string[];
  tier2ExampleSources: string[];
  tier3ExampleSources: string[];
  informationTypePriorities: string[];
  normalizationKeys: string[];
  crossGenreInformationTypeHints: string[];
  qualitySpecificRules: string[];
  defaultRiskLevel?: RiskLevel;
  officialVerificationRequired?: boolean;
  minimumIndependentSources?: number;
  scoringWeightOverrides?: Partial<GenreScoringWeights>;
  freshnessRules?: GenreFreshnessRule[];
  requiredFactFields?: string[];
  preferredCardTypes?: string[];
}

// ジャンル1〜26の共通ボイラープレート（三層構造の用途区分・標準鮮度テーブル・
// 除外ルール前半4項目）を適用しつつ、ジャンル固有の情報を差し込むビルダー。
function buildStandardGenreConfig(params: StandardGenreParams): GenreDetailedConfig {
  return {
    genreId: params.genreId,
    genreNumber: params.genreNumber,
    displayName: params.displayName,
    aliases: [],
    description: params.description,
    targetScope: params.targetScope,
    sourceLayers: {
      tier1: {
        purposes: TIER1_PURPOSES,
        sourceCategories: ["公式主体", "関係者・主催者公式"],
        exampleSources: params.tier1ExampleSources,
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: TIER2_PURPOSES,
        sourceCategories: ["中心専門媒体", "分野別媒体"],
        exampleSources: params.tier2ExampleSources,
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: TIER3_PURPOSES,
        sourceCategories: ["主要プラットフォーム", "SNS・コミュニティ"],
        exampleSources: params.tier3ExampleSources,
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: TIER3_PROHIBITED_USES,
      },
    },
    informationTypePriorities: params.informationTypePriorities,
    normalizationKeys: params.normalizationKeys,
    freshnessRules: params.freshnessRules ?? STANDARD_FRESHNESS_RULES,
    crossGenreInformationTypeHints: params.crossGenreInformationTypeHints,
    qualityAndSafetyRules: [...STANDARD_QUALITY_RULES_PREFIX, ...params.qualitySpecificRules],
    requiredFactFields: params.requiredFactFields ?? ["公式発表日時", "対象", "現在有効か"],
    preferredCardTypes: params.preferredCardTypes ?? ["official_announcement"],
    defaultRiskLevel: params.defaultRiskLevel ?? "normal",
    officialVerificationRequired: params.officialVerificationRequired ?? false,
    minimumIndependentSources: params.minimumIndependentSources ?? 1,
    scoringWeights: scoringWeights(params.scoringWeightOverrides),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  };
}

export const GENRE_CONFIGS: GenreDetailedConfig[] = [
  buildStandardGenreConfig({
    genreId: "music",
    genreNumber: 1,
    displayName: "音楽",
    description: "アーティストや作品、ライブ、リリース、出演、チャート、ファン向け情報を扱う。",
    targetScope: ["アーティスト・バンド", "新曲・アルバム", "ライブ・ツアー", "テレビ・ラジオ出演", "配信・チャート", "楽器・楽譜・演奏"],
    tier1ExampleSources: ["アーティスト公式", "所属事務所", "レーベル", "会場", "主催者", "配信元", "権利管理団体"],
    tier2ExampleSources: ["音楽ナタリー", "Billboard JAPAN", "BARKS", "リアルサウンド"],
    tier3ExampleSources: ["Spotify", "Apple Music", "YouTube", "チケットサービス", "ファンクラブ"],
    informationTypePriorities: ["new_release", "event_announcement", "ticket_sale", "tv_appearance", "collaboration"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["映画・テレビ：主題歌、劇伴、出演", "ラジオ：artist_radio、radio_live", "推し活：tour_goods、fan_event"],
    qualitySpecificRules: ["歌詞・楽譜・音源の全文転載を避ける。", "出演・発売・ライブ日程は公式を最優先する。"],
    preferredCardTypes: ["new_release", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "movie",
    genreNumber: 2,
    displayName: "映画",
    description: "劇場公開、配信、作品、出演者、予告、興行、レビューを扱う。",
    targetScope: ["邦画・洋画", "劇場公開", "配信・円盤", "予告・特報", "舞台挨拶", "映画祭", "興行成績"],
    tier1ExampleSources: ["作品公式", "配給会社", "制作会社", "映画館", "映画祭", "出演者・事務所"],
    tier2ExampleSources: ["映画.com", "シネマトゥデイ", "映画ナタリー", "キネマ旬報"],
    tier3ExampleSources: ["映画館上映検索", "配信サービス", "Filmarks"],
    informationTypePriorities: ["new_release", "event_announcement", "tv_appearance", "award"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["芸能人：cast_appearance", "音楽：theme_song、soundtrack", "旅行：filming_location"],
    qualitySpecificRules: ["公開日・上映館・配信期限を再確認する。", "レビューのネタバレを管理する。"],
    preferredCardTypes: ["new_release", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "tv_drama",
    genreNumber: 3,
    displayName: "テレビ・ドラマ",
    description: "番組、放送回、出演、見逃し、改編、視聴情報を扱う。",
    targetScope: ["地上波・BS・CS", "ドラマ", "バラエティ", "ドキュメンタリー", "特番", "再放送・見逃し"],
    tier1ExampleSources: ["放送局", "番組", "制作会社", "配信サービス", "出演者"],
    tier2ExampleSources: ["テレビ情報誌", "ORICON NEWS", "MANTANWEB", "TVガイド系媒体"],
    tier3ExampleSources: ["TVer", "NHKプラス", "番組表"],
    informationTypePriorities: ["tv_appearance", "event_announcement", "catch_up"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["芸能人：tv_appearance", "音楽：music_program", "ラジオ：program_spinoff"],
    qualitySpecificRules: ["放送地域・放送時間・配信期限を保持する。", "未確認の番組終了・降板情報を断定しない。"],
    preferredCardTypes: ["tv_appearance", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "anime",
    genreNumber: 4,
    displayName: "アニメ",
    description: "作品、放送・配信、映画、声優、イベント、商品を扱う。",
    targetScope: ["テレビアニメ", "劇場版", "配信", "声優", "イベント", "主題歌", "商品・コラボ"],
    tier1ExampleSources: ["作品公式", "制作会社", "放送局", "配信元", "出版社", "版権元", "声優事務所"],
    tier2ExampleSources: ["アニメ！アニメ！", "コミックナタリー", "AnimeJapan関連"],
    tier3ExampleSources: ["配信サービス", "公式YouTube", "イベント・チケット"],
    informationTypePriorities: ["new_release", "event_announcement", "youtube_appearance", "collaboration"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["漫画：原作", "音楽：主題歌", "キャラクター：character_goods", "推し活：voice_actor_event"],
    qualitySpecificRules: ["違法アップロード・海賊版を除外する。", "放送版・配信版・劇場版を別バージョンとして管理する。"],
    preferredCardTypes: ["new_release", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "manga_comic",
    genreNumber: 5,
    displayName: "漫画・コミック",
    description: "連載、単行本、電子書籍、休載、完結、展覧会を扱う。",
    targetScope: ["少年・少女・青年漫画", "Web漫画", "単行本", "電子版", "連載・休載", "漫画賞", "原画展"],
    tier1ExampleSources: ["出版社", "雑誌", "作品", "作者", "電子書店", "展覧会主催者"],
    tier2ExampleSources: ["コミックナタリー", "出版社系媒体", "漫画専門誌・書評"],
    tier3ExampleSources: ["電子書店", "マンガアプリ", "pixivコミック"],
    informationTypePriorities: ["new_release", "hiatus", "return"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["アニメ：adaptation", "映画・ドラマ：live_action", "キャラクター：goods", "アート：original_art_exhibition"],
    qualitySpecificRules: ["漫画本文・画像の大量転載を避ける。", "休載・再開・発売日は出版社公式で確認する。"],
    preferredCardTypes: ["new_release"],
  }),
  buildStandardGenreConfig({
    genreId: "book_reading",
    genreNumber: 6,
    displayName: "書籍・読書",
    description: "新刊、著者、書評、受賞、復刊、図書館、読書イベントを扱う。",
    targetScope: ["小説", "新書・実用書", "児童書", "雑誌", "電子書籍", "文学賞", "書店イベント"],
    tier1ExampleSources: ["出版社", "著者", "書店", "図書館", "文学賞主催者"],
    tier2ExampleSources: ["好書好日", "本の雑誌", "ダ・ヴィンチWeb"],
    tier3ExampleSources: ["Amazon", "楽天ブックス", "honto", "読書メーター"],
    informationTypePriorities: ["new_release", "award", "event_announcement"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["映画・ドラマ：adaptation", "歴史：history_book", "ラジオ：author_interview、audiobook"],
    qualitySpecificRules: ["本文の長文転載を避ける。", "版・翻訳・電子版・文庫化を区別する。"],
    preferredCardTypes: ["new_release", "award"],
  }),
  buildStandardGenreConfig({
    genreId: "game",
    genreNumber: 7,
    displayName: "ゲーム",
    description: "新作、アップデート、イベント、攻略、eスポーツ、障害を扱う。",
    targetScope: ["家庭用・PC・スマホ", "発売・予約", "アップデート", "イベント", "障害・メンテナンス", "大会・eスポーツ"],
    tier1ExampleSources: ["メーカー", "開発会社", "運営", "ストア", "公式大会", "プラットフォーム"],
    tier2ExampleSources: ["4Gamer", "ファミ通.com", "GAME Watch", "IGN Japan"],
    tier3ExampleSources: ["Steam", "PlayStation", "Nintendo", "Xbox", "App Store", "Google Play"],
    informationTypePriorities: ["new_release", "preorder_start", "event_announcement", "defect"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["アニメ：game_anime", "音楽：game_music", "スポーツ：esports", "キャラクター：game_goods"],
    qualitySpecificRules: ["リークと公式発表を分離する。", "攻略情報はバージョンを保持する。", "チート・不正アクセス・RMT誘導を除外する。"],
    preferredCardTypes: ["new_release", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "celebrity_talent",
    genreNumber: 8,
    displayName: "芸能人・タレント",
    description: "人物単位の出演、活動、作品、イベント、公式発表を扱う。",
    targetScope: ["俳優", "タレント", "モデル", "文化人", "アナウンサー", "出演・イベント"],
    tier1ExampleSources: ["本人", "所属事務所", "番組", "作品", "主催者", "出版社"],
    tier2ExampleSources: ["ORICON NEWS", "モデルプレス", "各業界専門媒体"],
    tier3ExampleSources: ["本人SNS", "動画", "チケット", "ファンクラブ"],
    informationTypePriorities: ["tv_appearance", "magazine_feature", "event_announcement"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["映画・テレビ：appearance", "音楽：artist_activity", "ラジオ：celebrity_radio", "美容：brand_ambassador"],
    qualitySpecificRules: ["私生活・交際・健康・家族の未確認情報を扱わない。", "同姓同名をentity_idで識別する。"],
    defaultRiskLevel: "moderate",
    preferredCardTypes: ["tv_appearance", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "vtuber_streamer",
    genreNumber: 9,
    displayName: "VTuber・動画配信者",
    description: "チャンネル、配信予定、動画、出演、イベント、活動休止を扱う。",
    targetScope: ["VTuber", "YouTuber", "ストリーマー", "ライブ配信", "動画投稿", "コラボ", "イベント・グッズ"],
    tier1ExampleSources: ["本人・所属事務所", "公式チャンネル", "イベント", "販売元"],
    tier2ExampleSources: ["PANORA", "MoguLive", "CreatorZine"],
    tier3ExampleSources: ["YouTube", "Twitch", "ニコニコ", "ファンコミュニティ"],
    informationTypePriorities: ["live_stream", "youtube_appearance", "hiatus", "return"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["ゲーム：game_stream", "音楽：cover_song、live", "ラジオ：podcast", "推し活：fan_event"],
    qualitySpecificRules: ["切り抜きの許諾・公式性を管理する。", "卒業・休止・炎上を切り抜きだけで断定しない。", "なりすまし・音声クローンを除外する。"],
    defaultRiskLevel: "moderate",
    preferredCardTypes: ["live_stream", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "comedy_variety",
    genreNumber: 10,
    displayName: "お笑い・バラエティ",
    description: "芸人、ライブ、賞レース、番組、ラジオ、YouTubeを扱う。",
    targetScope: ["芸人・コンビ", "劇場・ライブ", "賞レース", "テレビ・ラジオ", "YouTube", "イベント"],
    tier1ExampleSources: ["本人・事務所", "劇場", "番組", "賞レース主催者", "チケット公式"],
    tier2ExampleSources: ["お笑いナタリー", "QJWeb"],
    tier3ExampleSources: ["劇場・チケット", "YouTube", "Podcast"],
    informationTypePriorities: ["event_announcement", "tv_appearance", "award"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["テレビ：variety_show", "ラジオ：comedian_radio", "舞台：comedy_live", "推し活：fan_event"],
    qualitySpecificRules: ["ネタ全文・有料公演の無断転載を避ける。", "冗談と事実発言を文脈で区別する。"],
    preferredCardTypes: ["event_announcement", "tv_appearance"],
  }),
  buildStandardGenreConfig({
    genreId: "stage_theater",
    genreNumber: 11,
    displayName: "舞台・演劇",
    description: "公演、劇団、出演者、チケット、配信、レビューを扱う。",
    targetScope: ["演劇", "ミュージカル", "2.5次元", "伝統芸能", "公演日程", "チケット・配信"],
    tier1ExampleSources: ["劇団", "制作", "劇場", "出演者", "主催者", "配信元"],
    tier2ExampleSources: ["ステージナタリー", "シアターテイメントNEWS", "演劇専門誌"],
    tier3ExampleSources: ["チケット", "配信", "劇場検索", "レビュー"],
    informationTypePriorities: ["ticket_sale", "cast_change", "cancellation"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["芸能人：stage_appearance", "音楽：musical", "アニメ：2_5d_stage", "歴史：traditional_performance"],
    qualitySpecificRules: ["配役変更・中止・当日券は公式で再確認する。", "舞台映像・台本の違法配信を除外する。"],
    preferredCardTypes: ["ticket_sale", "event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "sports_watching",
    genreNumber: 12,
    displayName: "スポーツ観戦",
    description: "大会、試合、チーム、選手、結果、放送、チケットを扱う。",
    targetScope: ["野球・サッカー等", "国内外リーグ", "代表戦", "大会", "順位・記録", "放送・配信", "観戦チケット"],
    tier1ExampleSources: ["競技団体", "リーグ", "チーム", "選手", "大会", "会場", "放送公式"],
    tier2ExampleSources: ["スポーツナビ", "各競技専門媒体", "新聞スポーツ面"],
    tier3ExampleSources: ["公式スコア", "チケット", "配信", "ファンコミュニティ"],
    informationTypePriorities: ["event_announcement", "ticket_sale", "cancellation"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["旅行：away_trip", "乗り物：motorsport", "ラジオ：live_commentary", "コレクション：team_goods"],
    qualitySpecificRules: ["試合結果・順位は公式データを優先する。", "移籍・故障・処分の噂を断定しない。", "違法配信を除外する。"],
    preferredCardTypes: ["event_announcement", "ticket_sale"],
  }),
  buildStandardGenreConfig({
    genreId: "sports_fitness",
    genreNumber: 13,
    displayName: "スポーツ・運動実践",
    description: "自分で行う運動、練習、教室、施設、用具、安全を扱う。",
    targetScope: ["ランニング", "筋力トレーニング", "球技", "水泳", "ヨガ", "武道", "教室・施設", "用具・大会参加"],
    tier1ExampleSources: ["競技団体", "施設", "指導者", "メーカー", "行政・健康安全機関"],
    tier2ExampleSources: ["Tarzan等の運動媒体", "競技別専門媒体", "専門家監修情報"],
    tier3ExampleSources: ["施設予約", "練習動画", "記録アプリ", "ウェアラブル"],
    informationTypePriorities: ["new_product", "event_announcement", "adverse_effect"],
    normalizationKeys: ["entity_id", "information_type", "target_date_or_release", "source_event_id"],
    crossGenreInformationTypeHints: ["健康：training_health", "料理：sports_meal", "アウトドア：trail_running", "ガジェット：fitness_device"],
    qualitySpecificRules: ["痛み・怪我・持病が関係する内容は医療相談を優先する。", "極端な減量・危険な負荷・無資格指導を避ける。"],
    defaultRiskLevel: "moderate",
    scoringWeightOverrides: { reliability: 0.19, urgency: 0.1 },
    preferredCardTypes: ["event_announcement", "health_notice"],
  }),
  buildStandardGenreConfig({
    genreId: "outdoor",
    genreNumber: 14,
    displayName: "アウトドア",
    description: "キャンプ、登山、釣り、雪山、水辺、自然観察などの現地活動を扱う。",
    targetScope: ["キャンプ", "登山・トレッキング", "釣り", "サイクリング", "スキー・雪山", "サーフィン・カヌー", "自然観察"],
    tier1ExampleSources: ["国・自治体・公園管理者", "キャンプ場・山小屋", "活動団体", "気象・防災・道路・交通", "メーカー"],
    tier2ExampleSources: ["山と溪谷オンライン", "YAMAP", "BE-PAL系"],
    tier3ExampleSources: ["キャンプ場予約", "ルート・活動記録", "アクティビティ予約", "ライブカメラ"],
    informationTypePriorities: ["seasonal_operation", "warning", "road_closure"],
    normalizationKeys: ["activity_id", "field_or_facility_id", "information_type", "target_date_or_season", "published_at"],
    crossGenreInformationTypeHints: ["旅行：camping_trip、mountain_trip", "スポーツ：trail_running、climbing", "自然：birdwatching、stargazing", "乗り物：car_camping"],
    qualitySpecificRules: [
      "公式閉鎖・通行止めを利用者投稿より優先する。",
      "火気、一酸化炭素、増水、雪崩、低体温、熱中症、火山、野生動物を厳格に扱う。",
      "山菜・きのこの食用判定をAIで行わない。",
    ],
    defaultRiskLevel: "moderate",
    officialVerificationRequired: true,
    scoringWeightOverrides: { reliability: 0.19, urgency: 0.11 },
    preferredCardTypes: ["safety_alert", "seasonal_info"],
  }),
  buildStandardGenreConfig({
    genreId: "travel",
    genreNumber: 15,
    displayName: "旅行・観光",
    description: "行き先発見から交通、宿泊、体験、現地安全までを扱う。",
    targetScope: ["国内・海外旅行", "観光地・温泉", "宿泊", "交通", "モデルコース", "現地体験", "入国・治安・災害"],
    tier1ExampleSources: ["観光庁・JNTO・外務省", "自治体・観光協会・DMO", "施設・宿泊・交通・主催者"],
    tier2ExampleSources: ["トラベルWatch", "じゃらんニュース", "旅色", "るるぶ", "地球の歩き方系"],
    tier3ExampleSources: ["楽天トラベル", "じゃらんnet", "宿泊予約", "体験予約"],
    informationTypePriorities: ["seasonal_operation", "event_announcement", "warning"],
    normalizationKeys: ["destination_or_facility_id", "information_type", "target_date_or_travel_period", "origin_region", "published_at"],
    crossGenreInformationTypeHints: ["グルメ：local_food、hotel_dining", "アウトドア：mountain_trip", "歴史：heritage_tour", "推し活：filming_location、fan_tour"],
    qualitySpecificRules: [
      "空室・料金・交通・天候は表示時再取得する。",
      "海外は外務省、入国条件、大使館等を確認する。",
      "口コミを営業時間・安全情報の確定に使わない。",
    ],
    officialVerificationRequired: true,
    preferredCardTypes: ["travel_recommendation", "safety_alert"],
  }),
  buildStandardGenreConfig({
    genreId: "theme_park_leisure",
    genreNumber: 16,
    displayName: "テーマパーク・レジャー施設",
    description: "施設の営業、アトラクション、イベント、チケット、混雑、休止を扱う。",
    targetScope: ["テーマパーク・遊園地", "動物園・水族館", "博物館・科学館", "屋内施設", "温浴・スパ", "ショー・パレード"],
    tier1ExampleSources: ["施設公式サイト・アプリ", "SNS", "運営会社", "自治体", "コラボ主催者"],
    tier2ExampleSources: ["Walkerplus", "いこーよ", "じゃらんニュース"],
    tier3ExampleSources: ["公式チケット", "体験予約", "混雑予測", "口コミ"],
    informationTypePriorities: ["temporary_closure", "event_announcement", "congestion"],
    normalizationKeys: ["facility_id", "area_or_attraction_id", "information_type", "target_date_or_event_period", "published_at"],
    crossGenreInformationTypeHints: ["旅行：theme_park_trip", "キャラクター：character_event", "自然：animal_exhibition", "グルメ：park_food"],
    qualitySpecificRules: [
      "当日情報にobserved_atとvalid_untilを持たせる。",
      "身長・年齢・健康条件は施設公式を優先する。",
      "転売、立入禁止、撮影禁止回避等の攻略を除外する。",
      "ショー・体験のネタバレを管理する。",
    ],
    preferredCardTypes: ["event_announcement", "facility_notice"],
  }),
  buildStandardGenreConfig({
    genreId: "gourmet_dining",
    genreNumber: 17,
    displayName: "グルメ・飲食",
    description: "飲食店、新店、限定メニュー、予約、地域グルメ、食品新商品を扱う。",
    targetScope: ["飲食店", "カフェ・スイーツ", "新規開店・閉店", "限定メニュー", "地域グルメ", "食品・飲料新商品", "予約・口コミ"],
    tier1ExampleSources: ["店舗・チェーン", "商業施設・ホテル", "自治体・商工会", "メーカー", "催事主催者"],
    tier2ExampleSources: ["グルメWatch", "えん食べ", "食品産業新聞"],
    tier3ExampleSources: ["食べログ", "ぐるなび", "ホットペッパー", "Retty"],
    informationTypePriorities: ["opening", "seasonal_limited", "recall"],
    normalizationKeys: ["restaurant_or_product_id", "branch_id", "information_type", "target_date_or_sale_period", "published_at"],
    crossGenreInformationTypeHints: ["料理：recipe、chef_recipe", "旅行：local_food", "イベント：food_festival", "嗜好飲料：craft_beer、wine_menu、coffee、tea"],
    qualitySpecificRules: [
      "開店予定と営業開始済みを区別する。",
      "アレルギー・回収は公式・行政情報のみで確定する。",
      "PR・招待・提供品を識別する。",
      "生成画像を実店舗・商品の写真として扱わない。",
    ],
    defaultRiskLevel: "moderate",
    preferredCardTypes: ["opening", "seasonal_info"],
  }),
  buildStandardGenreConfig({
    genreId: "cooking_baking",
    genreNumber: 18,
    displayName: "料理・お菓子作り",
    description: "家庭で作るレシピ、献立、技術、保存、製菓・製パン、安全を扱う。",
    targetScope: ["家庭料理", "献立・時短・節約", "お菓子・パン", "保存・下処理", "食事制限", "調理器具・家電"],
    tier1ExampleSources: ["食品・調味料・器具メーカー", "料理家・シェフ", "公的機関", "地域団体", "製菓材料店"],
    tier2ExampleSources: ["クラシル", "DELISH KITCHEN", "Nadia", "レタスクラブ", "macaroni"],
    tier3ExampleSources: ["クックパッド", "楽天レシピ", "ミールキット"],
    informationTypePriorities: ["new_product", "food_poisoning", "seasonal_limited"],
    normalizationKeys: ["dish_id", "recipe_variant", "creator_id", "cooking_method", "dietary_attributes"],
    crossGenreInformationTypeHints: ["グルメ：restaurant_reproduction", "書籍：cookbook", "スポーツ：sports_meal", "地域：local_cuisine"],
    qualitySpecificRules: [
      "食中毒・保存・低温調理は公的機関を最優先する。",
      "山菜・きのこ、ふぐ、生肉、瓶詰め、乳幼児、妊娠中、アレルギーを厳格に扱う。",
      "AI生成レシピを検証済みと表示しない。",
    ],
    defaultRiskLevel: "moderate",
    officialVerificationRequired: true,
    scoringWeightOverrides: { reliability: 0.19 },
    preferredCardTypes: ["recipe", "seasonal_info"],
  }),
  buildStandardGenreConfig({
    genreId: "fashion_beauty",
    genreNumber: 19,
    displayName: "ファッション・美容",
    description: "ブランド新作、コーディネート、コスメ、サロン、限定品を扱う。",
    targetScope: ["衣服・靴・バッグ", "アクセサリー", "コスメ・スキンケア", "ヘア・ネイル", "サロン", "美容家電", "美容医療"],
    tier1ExampleSources: ["ブランド・メーカー", "公式EC", "百貨店", "デザイナー・美容家", "サロン・クリニック"],
    tier2ExampleSources: ["WWDJAPAN", "FASHIONSNAP", "MAQUIA", "美的", "VOCE"],
    tier3ExampleSources: ["EC", "@cosme", "ホットペッパービューティー"],
    informationTypePriorities: ["new_product", "collaboration", "limited"],
    normalizationKeys: ["brand_id", "product_id", "season_or_collection", "color_or_variant", "information_type", "release_date"],
    crossGenreInformationTypeHints: ["芸能人：brand_ambassador", "推し活：artist_collaboration", "アート：fashion_photography", "ガジェット：beauty_device"],
    qualitySpecificRules: [
      "美容と美容医療を分離する。",
      "加工画像・AI画像・誇大な効果表現を識別する。",
      "極端な減量、容姿不安を煽る情報を下げる。",
    ],
    preferredCardTypes: ["new_product", "collaboration"],
  }),
  buildStandardGenreConfig({
    genreId: "art_photo_creation",
    genreNumber: 20,
    displayName: "アート・写真・創作",
    description: "展覧会、作家、作品、写真、イラスト、制作技法、公募を扱う。",
    targetScope: ["美術館・展覧会", "絵画・彫刻", "写真・写真展", "イラスト・デザイン", "デジタルアート", "公募・コンテスト", "制作機材・ソフト"],
    tier1ExampleSources: ["美術館・ギャラリー", "作家", "主催者", "文化行政", "公募主催者", "カメラ・画材・ソフトメーカー"],
    tier2ExampleSources: ["美術手帖", "artscape", "Tokyo Art Beat", "IMA ONLINE"],
    tier3ExampleSources: ["展覧会検索", "公募検索", "pixiv", "Behance", "ArtStation", "BOOTH"],
    informationTypePriorities: ["event_announcement", "new_product"],
    normalizationKeys: ["exhibition_id", "venue_id", "tour_version", "information_type", "event_period"],
    crossGenreInformationTypeHints: ["旅行：museum_trip、photo_trip", "漫画・アニメ：illustration_exhibition", "ファッション：fashion_photography", "ガジェット：camera_release"],
    qualitySpecificRules: [
      "作品画像の無断転載・高解像度再配布を避ける。",
      "AI生成は作者・サービス表示で識別し、作風だけで断定しない。",
      "公募の著作権譲渡・商用利用条件を表示する。",
    ],
    preferredCardTypes: ["event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "handmade_diy",
    genreNumber: 21,
    displayName: "ハンドメイド・DIY",
    description: "材料、工具、作り方、ワークショップ、作品販売、住まいの改善を扱う。",
    targetScope: ["アクセサリー・手芸", "レジン・編み物・裁縫", "木工・家具", "塗装・収納・補修", "作品販売", "ワークショップ"],
    tier1ExampleSources: ["材料・工具・建材メーカー", "手芸店", "ホームセンター", "作家・講師・工房"],
    tier2ExampleSources: ["Craftie", "minne・Creema読み物", "makit", "DIY FACTORY"],
    tier3ExampleSources: ["minne", "Creema", "iichi", "BOOTH"],
    informationTypePriorities: ["event_announcement", "new_product"],
    normalizationKeys: ["craft_recipe_id", "craft_type", "creator_id", "technique", "material_set", "difficulty"],
    crossGenreInformationTypeHints: ["アート：craft_art", "ファッション：sewing、accessory_making", "推し活：ita_bag、fan_goods", "ガジェット：3d_printer、laser_cutter"],
    qualitySpecificRules: [
      "レジン、溶剤、刃物、電動工具等の安全条件を保持する。",
      "電気・ガス・給排水・構造・高所は専門工事と分離する。",
      "型紙・レシピの商用利用条件を管理する。",
    ],
    defaultRiskLevel: "moderate",
    preferredCardTypes: ["event_announcement"],
  }),
  buildStandardGenreConfig({
    genreId: "vehicles",
    genreNumber: 22,
    displayName: "乗り物",
    description: "鉄道、自動車、バイク、航空、船舶、公共交通、技術・歴史を扱う。",
    targetScope: ["鉄道・バス", "自動車・バイク・自転車", "航空・空港", "船舶・フェリー", "新型車両", "運行・道路", "イベント・博物館"],
    tier1ExampleSources: ["運行事業者", "メーカー", "国土交通省・自治体", "道路・空港・港湾管理者", "博物館"],
    tier2ExampleSources: ["乗りものニュース", "鉄道コム", "Response.", "Car Watch"],
    tier3ExampleSources: ["予約・経路・地図", "中古車", "試乗レビュー"],
    informationTypePriorities: ["new_route", "timetable_revision", "suspension"],
    normalizationKeys: ["operator_id", "route_id", "vehicle_or_service_id", "information_type", "effective_date"],
    crossGenreInformationTypeHints: ["旅行：sightseeing_train、road_trip", "アウトドア：car_camping", "スポーツ：motorsport", "コレクション：railway_model"],
    qualitySpecificRules: [
      "運行情報は表示時再取得する。",
      "計画中・認可・工事・運行開始をstatus_typeで区別する。",
      "違法改造、危険運転、撮影立入り、事故原因の推測を除外する。",
    ],
    preferredCardTypes: ["local_news"],
  }),
  buildStandardGenreConfig({
    genreId: "plants_nature",
    genreNumber: 23,
    displayName: "植物・自然",
    description: "植物の栽培と、野鳥・昆虫・野生動物・星空・自然環境の観察を扱う。",
    targetScope: ["観葉植物・花", "家庭菜園・果樹", "多肉・盆栽", "病害虫・園芸資材", "野鳥・昆虫", "野生動物", "星空・地質", "自然公園・生物多様性"],
    tier1ExampleSources: ["環境省・自治体", "植物園・種苗会社・園芸団体", "自然公園・ビジターセンター", "研究機関"],
    tier2ExampleSources: ["NHK趣味の園芸", "園芸分野別媒体", "BIRDER"],
    tier3ExampleSources: ["園芸店・植物EC", "観察記録プラットフォーム"],
    informationTypePriorities: ["flowering", "peak_viewing", "wildlife_sighting", "harvest_start"],
    normalizationKeys: ["plant_or_species_id", "observation_region", "information_type", "observed_at_or_target_season"],
    crossGenreInformationTypeHints: ["アウトドア：birdwatching、flower_viewing、stargazing", "旅行：botanical_garden_trip、nature_tourism", "DIY：terrarium、garden_diy", "写真：wildlife_photography"],
    qualitySpecificRules: [
      "希少種・営巣地の正確な位置を制限する。",
      "野生動物への餌付け、捕獲、巣への接近を推奨しない。",
      "食用植物・きのこを画像やAIだけで判定しない。",
      "農薬・外来種・採取規制は公的情報を優先する。",
    ],
    scoringWeightOverrides: { freshness: 0.18 },
    preferredCardTypes: ["seasonal_info"],
  }),
  buildStandardGenreConfig({
    genreId: "history_culture",
    genreNumber: 24,
    displayName: "歴史・文化",
    description: "歴史人物・出来事、史跡、文化財、伝統、民俗、古文書、考古学を扱う。",
    targetScope: ["日本史・世界史", "人物・事件", "城・寺社・遺跡", "文化財・世界遺産", "古文書・古地図", "民俗・伝統芸能", "地域史"],
    tier1ExampleSources: ["文化庁", "国会図書館・公文書館", "博物館・研究機関", "自治体・教育委員会", "寺社・保存会", "大学・学会"],
    tier2ExampleSources: ["WEB歴史街道", "歴史人", "歴史・考古学専門誌"],
    tier3ExampleSources: ["文化遺産オンライン", "デジタルアーカイブ", "展覧会・史跡検索"],
    informationTypePriorities: ["event_announcement"],
    normalizationKeys: ["historical_entity_id", "era_or_date_range", "location_id", "information_type", "interpretation_version"],
    crossGenreInformationTypeHints: ["旅行：heritage_tour", "イベント：traditional_festival", "アート：historical_exhibition", "ゲーム・映像：historical_game、period_drama"],
    qualitySpecificRules: [
      "史実・学説・伝承・創作をhistorical_claim_statusで分離する。",
      "戦争・災害・差別を扇情化しない。",
      "非公開文化財・発掘地点・墓地の位置を制限する。",
      "無断立入り・採取を除外する。",
    ],
    scoringWeightOverrides: { evergreenValue: 0.08, urgency: 0.03 },
    preferredCardTypes: ["evergreen_knowledge"],
  }),
  buildStandardGenreConfig({
    genreId: "indoor_hobby_collection",
    genreNumber: 25,
    displayName: "ゲーム以外の室内趣味・コレクション",
    description: "模型、パズル、切手、貨幣、フィギュア、鉱物、アンティーク等を扱う。",
    targetScope: ["プラモデル・鉄道模型", "パズル・ミニチュア", "切手・貨幣", "鉱物・化石", "アンティーク", "フィギュア・記念品", "展示・保管"],
    tier1ExampleSources: ["メーカー", "発行機関", "博物館", "版権元", "イベント主催者", "鑑定団体"],
    tier2ExampleSources: ["Hobby JAPAN Web", "HOBBY Watch", "日本郵趣協会", "貨幣商協同組合"],
    tier3ExampleSources: ["公式EC", "専門店", "専門オークション", "フリマ"],
    informationTypePriorities: ["new_product", "reissue", "limited"],
    normalizationKeys: ["manufacturer_or_issuer", "product_or_catalog_id", "variant", "issue_or_release_date", "information_type"],
    crossGenreInformationTypeHints: ["乗り物：railway_model", "アニメ：character_figure", "歴史：historical_coin", "DIY：model_building、display_case_diy"],
    qualitySpecificRules: [
      "真贋を画像だけで断定しない。",
      "初版・再版・復刻・レプリカ・海賊版を区別する。",
      "出品価格を将来価値として断定しない。",
      "放射性鉱物、象牙、文化財、武器等の規制を確認する。",
    ],
    preferredCardTypes: ["new_product"],
  }),
  buildStandardGenreConfig({
    genreId: "radio_podcast",
    genreNumber: 26,
    displayName: "ラジオ・Podcast",
    description: "番組、放送回、出演者、ゲスト、聴き逃し、公開収録、音声コンテンツを扱う。",
    targetScope: ["AM・FM", "コミュニティFM", "インターネットラジオ", "Podcast", "ラジオドラマ", "番組改編", "公開収録・イベント"],
    tier1ExampleSources: ["放送局", "番組", "出演者", "制作会社・ネットワーク", "radiko等"],
    tier2ExampleSources: ["AUDIO START", "radiko news", "放送・Podcast業界媒体"],
    tier3ExampleSources: ["Apple Podcasts", "Spotify", "Amazon Music", "Audible", "YouTube"],
    informationTypePriorities: ["radio_appearance", "event_announcement"],
    normalizationKeys: ["program_id", "episode_id", "broadcast_or_publish_datetime", "episode_title", "version"],
    crossGenreInformationTypeHints: ["音楽：artist_radio", "お笑い：comedian_radio", "アニメ：voice_actor_radio", "歴史：history_podcast"],
    qualitySpecificRules: [
      "放送とPodcast、再編集版、動画版を区別する。",
      "聴取期限、地域制限、有料条件を保持する。",
      "切り抜き・文字起こしの公式性と検証状態を示す。",
      "冗談・意見・広告等の発言文脈を確認する。",
      "無許可音声クローンを除外する。",
    ],
    preferredCardTypes: ["radio_appearance"],
  }),

  // ジャンル27〜33は仕様書の記述が個別化されているため、個別に定義する。
  {
    genreId: "tabletop_games",
    genreNumber: 27,
    displayName: "ボードゲーム・カードゲーム・テーブルゲーム",
    aliases: [],
    description:
      "非デジタルのボードゲーム、カードゲーム、TRPG、マーダーミステリー、将棋・囲碁等について、新作、ルール、イベント、大会、店舗、コミュニティを扱う。",
    targetScope: ["ボードゲーム", "トレーディングカードゲーム", "デッキ構築型カードゲーム", "TRPG", "マーダーミステリー", "将棋・囲碁・チェス", "パズルゲーム", "ゲーム会・大会", "専門店・カフェ"],
    sourceLayers: {
      tier1: {
        purposes: ["発売日・内容物・対象年齢・プレイ人数・時間・ルール・エラッタ・再販・大会規定", "参加条件・会場・予約・定員・使用可能カード・禁止制限・賞品・開催変更", "公式戦・棋譜・結果・ルール"],
        sourceCategories: ["出版社・メーカー・作品公式", "大会・イベント・店舗公式", "競技団体・権利元"],
        exampleSources: ["出版社・メーカー公式", "大会運営公式", "将棋連盟・囲碁協会等の競技団体"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["新作・海外作品・業界ニュース・イベント・レビュー", "出展者・同人ゲーム・新作・会場情報", "ジャンル別専門解説・競技解説"],
        sourceCategories: ["専門メディア", "ゲームマーケット関連媒体", "TRPG・カード・伝統ゲーム専門媒体"],
        exampleSources: ["Table Games in the World", "ゲームマーケット関連媒体"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["作品情報・プレイ人数・時間・評価・拡張・言語依存の補完", "在庫・試遊・イベント・貸出・予約", "ルール説明・プレイ動画・デッキ解説・セッション報告"],
        sourceCategories: ["BoardGameGeek・国内データベース", "専門店・ボードゲームカフェ", "YouTube・配信・コミュニティ"],
        exampleSources: ["BoardGameGeek", "ボードゲームカフェ", "YouTube配信"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: TIER3_PROHIBITED_USES,
      },
    },
    informationTypePriorities: ["new_product", "event_announcement", "reissue"],
    normalizationKeys: ["game_id", "edition_or_expansion", "language_version", "information_type", "release_or_event_date"],
    freshnessRules: [
      { informationType: "新作・再販", preferredPeriod: "発表後〜発売後60日", revalidateAtDisplayTime: false },
      { informationType: "大会・ゲーム会", preferredPeriod: "募集開始〜終了", revalidateAtDisplayTime: true },
      { informationType: "ルール・エラッタ", preferredPeriod: "最新版を常時優先", revalidateAtDisplayTime: true },
      { informationType: "在庫・予約", preferredPeriod: "数分〜24時間", revalidateAtDisplayTime: true },
      { informationType: "レビュー", preferredPeriod: "発売後6〜12か月を優先", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["ゲーム：digital_adaptation", "地域イベント：board_game_meetup、tournament", "推し活：licensed_card_goods", "コレクション：rare_card、limited_edition"],
    qualityAndSafetyRules: [
      "海賊版、偽造カード、無断コピー、違法なルールブック共有を除外する。",
      "賭博性のある非合法な遊び方や金銭賭博を推奨しない。",
      "大会規定はエディション・シーズン・地域を保持する。",
      "TRPG・マーダーミステリーは重大なネタバレを管理する。",
    ],
    requiredFactFields: ["対象年齢", "プレイ人数", "ルールバージョン"],
    preferredCardTypes: ["new_product", "event_announcement"],
    defaultRiskLevel: "normal",
    officialVerificationRequired: false,
    minimumIndependentSources: 1,
    scoringWeights: scoringWeights(),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  },
  {
    genreId: "idol_fan_activity",
    genreNumber: 28,
    displayName: "アイドル・ファン活動",
    aliases: [],
    description: "アイドル、ファンクラブ、ライブ、特典会、投票、グッズ、聖地、応援活動など、ファンとして追う情報を扱う。",
    targetScope: ["アイドルグループ・メンバー", "ライブ・ツアー", "握手会・特典会", "ファンクラブ", "リリース・出演", "グッズ・写真・生誕祭", "応援広告・ファン企画", "卒業・加入"],
    sourceLayers: {
      tier1: {
        purposes: ["所属・メンバー・出演・ライブ・加入卒業・活動休止の確定", "発売・イベント・抽選・本人確認・持ち物・禁止事項の確認", "会員限定情報・先行・グッズ・デジタル特典・期限"],
        sourceCategories: ["本人・グループ・事務所公式", "レーベル・会場・番組・主催者公式", "ファンクラブ・公式ストア"],
        exampleSources: ["本人・グループ公式", "所属事務所", "ファンクラブ公式"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["インタビュー・ライブレポート・活動ニュース", "所属形態・活動規模別の媒体", "推し活市場・施設・商品・応援文化の補完"],
        sourceCategories: ["音楽・芸能・アイドル専門媒体", "女性・男性・地下・地域アイドル別媒体", "ファン文化・マーケティング媒体"],
        exampleSources: ["音楽・芸能専門媒体", "アイドル専門媒体"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["先行・一般販売・配信・グッズ在庫", "本人発信・ライブ告知・短尺動画・ファン反応", "交換・現場情報・初心者向け案内"],
        sourceCategories: ["チケット・配信・EC", "SNS・動画", "ファンコミュニティ"],
        exampleSources: ["チケットサービス", "本人SNS", "ファンコミュニティ"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: [...TIER3_PROHIBITED_USES, "公式規約を上回る情報としての利用"],
      },
    },
    informationTypePriorities: ["event_announcement", "ticket_sale", "resignation", "appointment"],
    normalizationKeys: ["idol_or_group_id", "member_id", "information_type", "event_or_release_id", "target_date"],
    freshnessRules: [
      { informationType: "ライブ・出演", preferredPeriod: "発表後〜終了", revalidateAtDisplayTime: false },
      { informationType: "チケット・抽選", preferredPeriod: "受付開始〜結果・公演終了", revalidateAtDisplayTime: true },
      { informationType: "グッズ", preferredPeriod: "発表後〜販売終了", revalidateAtDisplayTime: false },
      { informationType: "加入・卒業", preferredPeriod: "発表後〜実施後30日", revalidateAtDisplayTime: false },
      { informationType: "SNS投稿", preferredPeriod: "公開後7〜30日", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["音楽：release、tour", "芸能人：tv_appearance", "ラジオ：idol_radio", "キャラクター：collaboration_goods", "旅行：fan_tour、pilgrimage"],
    qualityAndSafetyRules: [
      "未確認の交際・私生活・住所・移動情報を扱わない。",
      "出待ち、追跡、無断撮影、個人情報特定、迷惑行為を助長しない。",
      "チケット・特典券の転売、偽造、名義貸しを除外する。",
      "ファン同士の攻撃、序列化、容姿中傷を増幅しない。",
      "卒業・活動休止・体調情報は本人・所属の表現を尊重する。",
    ],
    requiredFactFields: ["公式発表日時", "対象メンバー"],
    preferredCardTypes: ["event_announcement", "ticket_sale"],
    defaultRiskLevel: "moderate",
    officialVerificationRequired: false,
    minimumIndependentSources: 1,
    scoringWeights: scoringWeights(),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  },
  {
    genreId: "character_toys",
    genreNumber: 29,
    displayName: "キャラクター・玩具",
    aliases: [],
    description: "キャラクターIP、玩具、ぬいぐるみ、食玩、カプセルトイ、コラボ、施設・商品展開を扱う。",
    targetScope: ["キャラクター作品・ブランド", "ぬいぐるみ・玩具", "フィギュア・ドール", "食玩・カプセルトイ", "コラボ商品", "期間限定ショップ", "テーマ施設", "子ども向け玩具"],
    sourceLayers: {
      tier1: {
        purposes: ["名称・設定・記念日・イベント・商品・ライセンスの確認", "発売日・価格・対象年齢・仕様・安全基準・回収・再販", "ポップアップ・限定品・整理券・購入制限・開催期間の確認"],
        sourceCategories: ["版権元・キャラクター公式", "玩具メーカー・販売元公式", "施設・店舗・コラボ企業公式"],
        exampleSources: ["版権元公式", "玩具メーカー公式", "コラボ企業公式"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["新商品・展示会・予約・カプセルトイ・食玩", "作品ニュース・イベント・育児教育視点", "企業動向・IP展開・玩具市場"],
        sourceCategories: ["玩具・ホビー専門媒体", "キャラクター・子ども向け専門媒体", "ライセンス・玩具業界媒体"],
        exampleSources: ["HOBBY Watch", "キャラクター専門媒体"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["予約・在庫・再販・限定品の確認", "設置・入荷・稼働状況の補完", "開封・遊び方・コレクション・相場（真贋確認前提）"],
        sourceCategories: ["公式EC・正規玩具店", "カプセルトイ・アミューズメント店舗", "動画・SNS・中古市場"],
        exampleSources: ["正規玩具店EC", "アミューズメント店舗", "中古市場"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: [...TIER3_PROHIBITED_USES, "真贋の確認なしでの中古相場の一般化"],
      },
    },
    informationTypePriorities: ["new_product", "collaboration", "recall"],
    normalizationKeys: ["character_ip_id", "manufacturer_id", "product_id", "variant", "information_type", "release_date"],
    freshnessRules: [
      { informationType: "新商品", preferredPeriod: "発表後〜発売後60日", revalidateAtDisplayTime: false },
      { informationType: "予約・再販", preferredPeriod: "開始〜完売・終了", revalidateAtDisplayTime: true },
      { informationType: "ポップアップ", preferredPeriod: "発表後〜終了", revalidateAtDisplayTime: false },
      { informationType: "回収・事故", preferredPeriod: "発表後〜対応完了", revalidateAtDisplayTime: true },
      { informationType: "中古相場", preferredPeriod: "直近30〜90日", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["アニメ・漫画：character_origin", "テーマパーク：character_event", "推し活：fan_goods", "コレクション：figure_collection", "ファッション：character_apparel"],
    qualityAndSafetyRules: [
      "対象年齢、小部品、磁石、電池、ひも、塗料等の安全情報を優先する。",
      "偽物、海賊版、非公式グッズを識別する。",
      "子どもの購買を過度に煽る表現を抑える。",
      "ランダム商品・高額転売・コンプリート要求を投資価値として推奨しない。",
    ],
    requiredFactFields: ["対象年齢", "安全基準"],
    preferredCardTypes: ["new_product", "collaboration"],
    defaultRiskLevel: "moderate",
    officialVerificationRequired: false,
    minimumIndependentSources: 1,
    scoringWeights: scoringWeights(),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  },
  {
    genreId: "stationery_planner",
    genreNumber: 30,
    displayName: "文房具・手帳",
    aliases: [],
    description: "筆記具、ノート、紙製品、手帳、整理術、限定品、イベント、使い方を扱う。",
    targetScope: ["万年筆・ボールペン・シャープペン", "ノート・紙・付箋", "手帳・日記・家計簿", "画材・レタリング", "収納・デスク用品", "限定色・コラボ", "文具イベント・店舗"],
    sourceLayers: {
      tier1: {
        purposes: ["発売日・色・芯径・インク・紙質・サイズ・限定・回収の確認", "在庫・先行・限定・試筆・イベント・購入制限", "年度版・開始月・フォーマット・リフィル・使い方の確認"],
        sourceCategories: ["メーカー・ブランド公式", "公式EC・店舗・百貨店", "手帳出版社・公式コミュニティ"],
        exampleSources: ["文具メーカー公式", "手帳出版社公式"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["新商品・レビュー・展示会・業界ニュース", "万年筆・インク・紙・手帳等の専門情報", "ノート術・手帳術・学習仕事活用の補完"],
        sourceCategories: ["文具専門誌", "分野別媒体", "整理・仕事術媒体"],
        exampleSources: ["文具のとびら", "趣味の文具箱"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["在庫・限定・予約・試筆イベントの確認", "書き味・色見本・手帳デコ・活用例の補完", "廃番・限定インク・過年度品（状態・真贋確認前提）"],
        sourceCategories: ["文具店・EC", "YouTube・Instagram・ブログ", "フリマ・中古・交換"],
        exampleSources: ["文具店EC", "YouTube・Instagram"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: [...TIER3_PROHIBITED_USES, "色見本の撮影条件差を無視した断定"],
      },
    },
    informationTypePriorities: ["new_product", "limited", "seasonal_limited"],
    normalizationKeys: ["manufacturer_id", "product_id", "color_or_size_variant", "edition_year", "information_type", "release_date"],
    freshnessRules: [
      { informationType: "新商品", preferredPeriod: "発表後〜発売後60日", revalidateAtDisplayTime: false },
      { informationType: "限定・予約", preferredPeriod: "開始〜終了・完売", revalidateAtDisplayTime: true },
      { informationType: "手帳年度版", preferredPeriod: "発売前90日〜対象年終了", revalidateAtDisplayTime: false },
      { informationType: "在庫・再入荷", preferredPeriod: "数分〜24時間", revalidateAtDisplayTime: true },
      { informationType: "基本の使い方", preferredPeriod: "長期利用可能", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["学習：study_planner、note_taking", "仕事：business_notebook", "アート：lettering、sketch", "推し活：fan_planner、decorated_notebook", "コレクション：limited_ink、vintage_pen"],
    qualityAndSafetyRules: [
      "色見本は撮影条件・紙・画面で異なることを示す。",
      "インク、接着剤、カッター等の安全と素材適合を確認する。",
      "限定品の高額転売・投資価値を煽らない。",
      "個人の手帳画像から住所・予定・勤務先等を露出しない。",
    ],
    requiredFactFields: ["発売日", "仕様"],
    preferredCardTypes: ["new_product"],
    defaultRiskLevel: "normal",
    officialVerificationRequired: false,
    minimumIndependentSources: 1,
    scoringWeights: scoringWeights(),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  },
  {
    genreId: "gadgets_digital",
    genreNumber: 31,
    displayName: "ガジェット・デジタル機器",
    aliases: [],
    description: "スマートフォン、PC、周辺機器、カメラ、家電、ウェアラブル、ソフト更新、障害・安全情報を扱う。",
    targetScope: ["スマートフォン・タブレット", "PC・モニター", "イヤホン・オーディオ", "カメラ", "スマートウォッチ", "スマートホーム", "充電・バッテリー", "AI端末・アプリ", "発売・価格・アップデート"],
    sourceLayers: {
      tier1: {
        purposes: ["仕様・対応OS・発売日・価格・保証・アップデート・回収の確認", "リリースノート・障害・セキュリティ・料金・対応機種の確認", "技適・電気安全・バッテリー事故・リコール・脆弱性情報"],
        sourceCategories: ["メーカー・製品公式", "OS・アプリ・サービス公式", "行政・認証・安全機関"],
        exampleSources: ["メーカー公式", "OS/サービス公式", "行政・安全機関"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["カテゴリ別の速報・レビュー・技術解説", "製品・サービス・業界動向の補完", "性能・規格・開発者向け情報"],
        sourceCategories: ["PC Watch・ケータイ Watch・AV Watch・デジカメ Watch等", "ITmedia・CNET Japan等", "専門技術媒体・一次ベンチマーク"],
        exampleSources: ["PC Watch", "ケータイWatch", "ITmedia", "CNET Japan"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["価格・予約・在庫・構成・保証の確認", "複数店舗価格・利用体験・長期使用の補完", "実機・設定・故障例（個別例を一般化しない）"],
        sourceCategories: ["公式EC・正規販売店", "価格比較・レビュー", "動画・掲示板・SNS"],
        exampleSources: ["価格比較サイト", "レビューサイト"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: [...TIER3_PROHIBITED_USES, "個別の故障例を一般的な不具合として扱うこと"],
      },
    },
    informationTypePriorities: ["new_product", "security_incident", "accident", "defect"],
    normalizationKeys: ["manufacturer_id", "product_family", "model_number", "region_variant", "information_type", "release_or_update_date"],
    freshnessRules: [
      { informationType: "新製品", preferredPeriod: "発表後〜発売後90日", revalidateAtDisplayTime: false },
      { informationType: "価格・在庫", preferredPeriod: "数分〜24時間", revalidateAtDisplayTime: true },
      { informationType: "ソフト更新", preferredPeriod: "公開後30日、重大不具合は解消まで", revalidateAtDisplayTime: true },
      { informationType: "障害", preferredPeriod: "発生〜復旧", revalidateAtDisplayTime: true },
      { informationType: "リコール・脆弱性", preferredPeriod: "対応完了まで", revalidateAtDisplayTime: true },
      { informationType: "レビュー", preferredPeriod: "発売後6〜12か月を優先", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["写真：camera_release", "乗り物：dashcam、car_navigation", "スポーツ：fitness_device", "DIY：3d_printer", "美容：beauty_device"],
    qualityAndSafetyRules: [
      "バッテリー、充電器、発熱、感電、発火、リコール情報を優先する。",
      "脆弱性・セキュリティは公式アドバイザリを確認する。",
      "違法改造、認証回避、DRM回避、不正アクセスを助長しない。",
      "提供機・広告・アフィリエイトを識別する。",
      "発売前リークと正式情報を分離する。",
    ],
    requiredFactFields: ["型番", "対応OS", "発売日"],
    preferredCardTypes: ["new_product", "safety_alert"],
    defaultRiskLevel: "moderate",
    officialVerificationRequired: true,
    minimumIndependentSources: 1,
    scoringWeights: scoringWeights({ reliability: 0.19, urgency: 0.1 }),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  },
  {
    genreId: "pets_animals",
    genreNumber: 32,
    displayName: "ペット・動物・生き物",
    aliases: [],
    description: "犬、猫、小動物、鳥、魚、爬虫類、昆虫等について、飼育、医療、用品、施設、保護・譲渡、動物福祉を扱う。",
    targetScope: ["犬・猫", "小動物・鳥", "魚・爬虫類・両生類", "昆虫・エキゾチックアニマル", "ペットフード・用品", "動物病院・予防", "トリミング・ホテル・しつけ", "保護・譲渡・迷子", "動物園・水族館", "防災・動物福祉"],
    sourceLayers: {
      tier1: {
        purposes: ["法令・適正飼養・動物取扱業・マイクロチップ・収容譲渡・災害対応", "病気・予防・ワクチン・中毒・救急・治療・感染症", "対象種年齢・原材料・給与量・使用方法・回収・サービス条件"],
        sourceCategories: ["環境省・自治体・動物愛護機関", "動物病院・獣医師会・研究機関", "フード・用品メーカー、施設公式"],
        exampleSources: ["環境省・自治体", "動物病院・獣医師会", "フード・用品メーカー公式"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["犬猫の飼育・行動・しつけ・季節対策", "鳥・うさぎ・魚・爬虫類・昆虫等の対象種別情報", "医療・福祉・保護・業界情報の補完"],
        sourceCategories: ["いぬのきもち・ねこのきもち", "動物種別専門媒体", "動物福祉・獣医療専門媒体"],
        exampleSources: ["いぬのきもち", "ねこのきもち", "動物種別専門媒体"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["対応動物・診療時間・救急・予約・口コミの補完", "募集状態・条件・地域・連絡先", "日常の工夫・用品使用感（診断には使わない）"],
        sourceCategories: ["病院・サービス検索", "保護団体・譲渡会・迷子情報", "動画・SNS・飼育コミュニティ"],
        exampleSources: ["病院検索サービス", "保護団体・譲渡会情報"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: [...TIER3_PROHIBITED_USES, "症状・投薬の診断"],
      },
    },
    informationTypePriorities: ["infectious_disease", "recall", "recruitment"],
    normalizationKeys: ["species_id", "breed_or_variety", "life_stage", "information_type", "health_or_care_context"],
    freshnessRules: [
      { informationType: "医療・感染症", preferredPeriod: "最新情報を優先", revalidateAtDisplayTime: true },
      { informationType: "病院営業時間", preferredPeriod: "表示時再確認", revalidateAtDisplayTime: true },
      { informationType: "フード・用品新商品", preferredPeriod: "発売後60日", revalidateAtDisplayTime: false },
      { informationType: "回収", preferredPeriod: "対応完了まで", revalidateAtDisplayTime: true },
      { informationType: "譲渡・迷子", preferredPeriod: "募集中〜解決", revalidateAtDisplayTime: true },
      { informationType: "基本飼育", preferredPeriod: "長期利用可能、最新版確認", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["旅行：pet_friendly_trip", "施設：animal_exhibition", "地域イベント：adoption_event、pet_event", "DIY：pet_goods_diy", "ガジェット：pet_camera、automatic_feeder"],
    qualityAndSafetyRules: [
      "最優先は、かわいさや話題性ではなく、動物福祉、飼育責任、人と動物の安全、生態系保全とする。",
      "症状・誤飲・中毒・投薬は一般記事で診断せず、獣医師への相談を促す。",
      "人間用薬、精油、食品、植物等は動物種ごとの毒性を確認する。",
      "恐怖・苦痛を与える演出、違法飼育、密輸、無許可繁殖、飼育放棄を助長する内容を除外する。",
      "野生動物と飼育動物を区別し、外来種・放流・捕獲規制を確認する。",
    ],
    requiredFactFields: ["対象種", "健康・安全上の注意"],
    preferredCardTypes: ["health_notice", "adoption_event"],
    defaultRiskLevel: "high",
    officialVerificationRequired: true,
    minimumIndependentSources: 2,
    scoringWeights: scoringWeights({ reliability: 0.2, urgency: 0.1, userPreference: 0.03 }),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
    highRiskWarning: {
      triggerInformationTypes: ["poisoning", "adverse_effect", "food_poisoning", "warning", "alert", "recall"],
      lines: [
        "緊急時は自己判断せず、まず動物病院または専門機関（動物病院・中毒に関する専門相談窓口等）へ連絡してください。",
        "この情報は個別の診断・治療の代わりにはなりません。自己判断で吐かせる等の処置をしないでください。",
        "動物種・体重・摂取量・症状により対応が異なります。必ず個別に獣医師等の専門家へ確認してください。",
      ],
    },
    professionalSourcePatterns: {
      facility: /動物病院|動物医療センター|どうぶつ病院|動物クリニック/,
      corroborating: /獣医師|院長|監修|診療科|診療時間|所在地|アクセス|電話|TEL/,
    },
  },
  {
    genreId: "local_events_festivals",
    genreNumber: 33,
    displayName: "地域イベント・祭り",
    aliases: [],
    description: "地域の祭り、マルシェ、花火、講座、交流会、展示、地域スポーツ、行政・商業イベントなどを扱う。",
    targetScope: ["祭り・伝統行事", "花火・イルミネーション", "マルシェ・物産展", "地域ライブ・文化祭", "講座・セミナー", "交流会・コミュニティイベント", "自治体・商業施設イベント", "子ども・家族向け", "地域スポーツ・体験"],
    sourceLayers: {
      tier1: {
        purposes: ["開催日・場所・主催・交通規制・災害対応・申込・変更中止の確認", "プログラム・出演・出店・チケット・定員・持ち物・注意事項の確認", "道路規制・臨時交通・荒天・避難・安全情報"],
        sourceCategories: ["自治体・観光協会・公共施設公式", "主催者・実行委員会・会場公式", "警察・消防・交通・気象公式"],
        exampleSources: ["自治体・観光協会公式", "主催者・実行委員会公式", "警察・消防・気象庁"],
        allowedUses: TIER1_ALLOWED_USES,
        prohibitedUses: TIER1_PROHIBITED_USES,
      },
      tier2: {
        purposes: ["地域横断のイベント発見・季節特集", "小規模イベント・地域ニュース・取材記事", "内容に応じた分野別イベント情報"],
        sourceCategories: ["Walkerplus・地域情報媒体", "地方新聞・放送局・タウン情報", "イベント分野別媒体"],
        exampleSources: ["Walkerplus", "地方新聞・放送局"],
        allowedUses: TIER2_ALLOWED_USES,
        prohibitedUses: TIER2_PROHIBITED_USES,
      },
      tier3: {
        purposes: ["日付・地域・予約・空席の横断", "小規模・直前告知の補完", "現地状況・混雑・参加体験（開催可否は公式優先）"],
        sourceCategories: ["イベント検索・チケット", "商業施設・店舗・学校・団体SNS", "地域コミュニティ・口コミ"],
        exampleSources: ["イベント検索サービス", "商業施設SNS"],
        allowedUses: TIER3_ALLOWED_USES,
        prohibitedUses: [...TIER3_PROHIBITED_USES, "開催可否の確定"],
      },
    },
    informationTypePriorities: ["event_announcement", "cancellation", "traffic_restriction"],
    normalizationKeys: ["event_id", "organizer_id", "venue_id", "start_datetime", "event_category", "information_type"],
    freshnessRules: [
      { informationType: "開催予定", preferredPeriod: "発表後〜終了", revalidateAtDisplayTime: false },
      { informationType: "申込・抽選", preferredPeriod: "受付開始〜結果・終了", revalidateAtDisplayTime: true },
      { informationType: "当日変更・中止", preferredPeriod: "即時〜終了", revalidateAtDisplayTime: true },
      { informationType: "交通規制", preferredPeriod: "発表後〜解除", revalidateAtDisplayTime: true },
      { informationType: "開催レポート", preferredPeriod: "終了後30日", revalidateAtDisplayTime: false },
      { informationType: "定例行事", preferredPeriod: "次回日程を毎年再確認", revalidateAtDisplayTime: false },
    ],
    crossGenreInformationTypeHints: ["旅行：local_trip", "グルメ：food_festival、market", "音楽：local_concert", "歴史：traditional_festival", "スポーツ：local_tournament", "ペット：adoption_event"],
    qualityAndSafetyRules: [
      "開催中止・変更・交通規制は主催者・自治体・警察等を最優先する。",
      "過去年の告知を今年の開催情報として扱わない。",
      "無許可イベント、危険な群集行動、違法露店、未成年飲酒等を推奨しない。",
      "住所・連絡先が個人宅の場合は公開範囲に配慮する。",
      "災害・荒天・熱中症・雑踏事故の安全情報を優先する。",
      "お酒・嗜好飲料イベントはeventとして扱い、商品・飲食内容はグルメ・飲食へ横断する。",
    ],
    requiredFactFields: ["開催日時", "会場", "主催者"],
    preferredCardTypes: ["event_announcement", "safety_alert"],
    defaultRiskLevel: "moderate",
    officialVerificationRequired: true,
    minimumIndependentSources: 1,
    scoringWeights: scoringWeights({ regionalFit: 0.1, freshness: 0.16 }),
    configurationVersion: 1,
    lastVerifiedAt: IMPLEMENTATION_DATE,
  },
];

export const GENRE_CONFIG_BY_ID: Map<string, GenreDetailedConfig> = new Map(
  GENRE_CONFIGS.map((c) => [c.genreId, c]),
);

export function getGenreConfig(genreId: string): GenreDetailedConfig | undefined {
  return GENRE_CONFIG_BY_ID.get(genreId);
}

// 既存の自由記述カテゴリ列（parentCategory/subCategory/detailCategory、非推奨）を、
// 新しい固定33ジャンル体系（primaryGenreId/secondaryGenreIds/informationTypes）から
// 後方互換のために自動生成する。既存UI・既存カラムを壊さないための橋渡し関数。
export function deriveLegacyCategoryFields(
  primaryGenreId: string,
  secondaryGenreIds: string[],
  informationTypes: string[],
): { parentCategory: string; subCategory: string; detailCategory: string } {
  const primaryConfig = getGenreConfig(primaryGenreId);
  const secondaryConfig = secondaryGenreIds.length > 0 ? getGenreConfig(secondaryGenreIds[0]) : undefined;

  return {
    parentCategory: primaryConfig?.displayName ?? "未分類",
    subCategory: secondaryConfig?.displayName ?? primaryConfig?.displayName ?? "未分類",
    detailCategory: informationTypes.length > 0 ? informationTypes.join("・") : "詳細未分類",
  };
}
